# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-05 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='fk_user_id',
        ),
    ]
