# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200106_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_address_now',
            field=models.CharField(default='', max_length=100, verbose_name='目前居住地'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_certificate',
            field=models.CharField(default='', max_length=20, verbose_name='证书'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_self_assessment',
            field=models.CharField(default='', max_length=200, verbose_name='自我评价'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_teaching_area',
            field=models.CharField(default='', max_length=20, verbose_name='可授课区域'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_teaching_way',
            field=models.CharField(default='', max_length=20, verbose_name='授课方式'),
        ),
    ]
