# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200107_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_tutor_type',
            field=models.CharField(default='', max_length=20, verbose_name='身份类型'),
        ),
    ]
