# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200107_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_education',
            field=models.CharField(max_length=30, verbose_name='学历'),
        ),
    ]
