# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200107_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(max_length=20, verbose_name='年级名称'),
        ),
    ]
