# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-09 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200108_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_assessment',
            field=models.CharField(default='', max_length=200, verbose_name='自我评价'),
        ),
    ]
