# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_order', models.CharField(max_length=14, unique=True, verbose_name='订单编号')),
                ('user_order_createtime', models.CharField(max_length=30, verbose_name='订单创建时间')),
                ('fk_urser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User')),
            ],
            options={
                'db_table': 'userorder',
            },
        ),
    ]
