# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_zan_user_order_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zan',
            name='user_order_isActive',
        ),
        migrations.AddField(
            model_name='userorder',
            name='user_order_isActive',
            field=models.BooleanField(default='False', verbose_name='是否激活'),
        ),
    ]
