# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_userorder_user_pay_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='course_grade_name',
            field=models.CharField(default='', max_length=30, verbose_name='年级科目'),
        ),
    ]
