# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_userorder_course_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_article_title', models.CharField(max_length=50, verbose_name='文章题目')),
                ('teacher_article_content', models.TextField(verbose_name='文章内容')),
                ('fk_teahcer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Teacher')),
            ],
            options={
                'db_table': 'teacherarticle',
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_article_title', models.CharField(max_length=50, verbose_name='文章题目')),
                ('user_article_content', models.TextField(verbose_name='文章内容')),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User')),
            ],
            options={
                'db_table': 'userarticle',
            },
        ),
    ]
