# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_teacherarticle_userarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherarticle',
            name='create_time',
            field=models.CharField(default='', max_length=30, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='create_time',
            field=models.CharField(default='', max_length=30, verbose_name='创建时间'),
        ),
    ]
